### ISSUE TITLE
Thread-1 WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger

### ISSUE THREAD

**Issue by Davmira** [Rbillon59/jmeter-k8s-starterkit#9]
Hello @Rbillon59,

Thanks for this starterkit, it's very helpfull.
I have an issue when launching the test, I keep getting the same error :
![image](https://user-images.githubusercontent.com/6617187/145470824-1472f617-eb53-49e2-9107-4149e95e20f2.png)

Sadly I can't get the report from the master node because it stopped and grafana has no data.
I tried with this command : ./start_test.sh -j my-scenario.jmx -n default -c -m -i 5 -r
I am using the demo test since I haven't developed mine for now.
Thanks

**Comment by Rbillon59** [comment]
Hi @Davmira 

Thanks you for your feedback, I'll take a look asap.

**Comment by Rbillon59** [comment]
Just checked, 

The WARN log you are seeing is linked to the ` PluginsManagerCMD.sh ` script used by JMeter to install the plugins with the command line (by analysing the JMX needs). If your terminal is hangging on this message, hitting CTRL +C will not stop the test and you'll be able to recover your terminal. So don't worry, your test is executing well behind the scene !

But you are right. In the default scenario I did not add the BackendListener with the default influxdb connection, thus, you've not your result uploaded in it. I added it in the PR linked to this comment.

Also, I made a mistake in the result location in the README, the result location are not : <master-pod-id>:/opt/jmeter/apache-jmeter/bin/<result>

But it's stored in <master-pod-id>:/report

Would you take the time to checkout the fix branch I created to test it again please ? 

The PR branch is : #10 

Thanks you,
Romain

**Comment by Davmira** [comment]
Thank you for the quick reply.

I have checkout your new branch add-influxdb-listener-to-default-jmx, and I still have the same issue :
![jmeter still not working](https://user-images.githubusercontent.com/6617187/145638101-15171aa9-1f57-43b4-bce3-63ffa9f6cd0a.png)

As you can see I am on your branch (I have checked the two files you have changed) and the master pod stopped. CTRL+C or not the test have stopped, I think so I can't go inside the master pod and get the report at the path : /report.

**Comment by Rbillon59** [comment]
Ok I guess I've understand what I've missed here.

Do you confirm that the test is executing correctly and the master pod is in completed state after the rest execution ? Or it just get completed directly after the end of the script ?

Effectively when the master is done, the pod is deleted by the cleaner job. So to recover, a new master needs to be deployed (by default, the master command is to wait indefinitely). So I need to update the readme or create a script.. I'll think about a solution quickly and update the PR.

Thanks again

**Comment by Rbillon59** [comment]
I pushed a commit to explain how to get the report if the master pod have been cleaned by the cronjob. Let me know if it's understandable and it cover your use case please.

Thanks you

**Comment by Davmira** [comment]
No, I don't think the execution finish well, I still have the WARN Unable to register Log4j error. At the end now, the master pod is in state NotReady and no more completed :
![start bug no end execution](https://user-images.githubusercontent.com/6617187/145720942-4b364c1a-155f-41b9-a8a0-b41c5441b986.png)

Also, the grafana graph is empty and if I restart a master pod there is nothing at the path /result : 
![jmeter not working nothing in master pod](https://user-images.githubusercontent.com/6617187/145720962-48028cf5-1594-4d0f-9912-98d5c560c680.png)

Since today I also have those warnings at the start :
![warning start](https://user-images.githubusercontent.com/6617187/145721030-474cb35d-f357-4a02-b234-b20d0d9875a2.png)


Thanks for the update anyway and let's keep in touch.

**Comment by Rbillon59** [comment]
Hi, 

It seems I'm missing somethings because I tested everything locally on docker-desktop on windows and on minikube on Linux. Everything was working well.

To be able to go deeper on your problem, could you provide me the following infos :

- Kubernetes version
- Kubernetes provider 
- JMeter logs (should be on stdout of the slaves and master pods)

About the Kubernetes warning, it happen when you try to make a kubectl apply on resources created with the kubectl create command. I've used the create command and not apply because the Grafana config maps of the dashboard are too heavy to be created with kubectl apply.

Thanks you

**Comment by Davmira** [comment]
Hello,

My kubernetes version :
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

I am using rancher to manage my cluster and my provider is open stack.
I have :

- 2 control nodes : 4 Cores / 14.6 GiB
- 3 etcd nodes : 4 Cores / 14.6 GiB
- 6 workers nodes : 4 Cores / 14.6 GiB

I am using CentOS Linux 7 images on my workers because I needed it for another project.

My output of my master and slave pod (I guess it was you mean by stdout) :

`09:03:12 airflow@paqctdm:[~]: kubectl describe pod jmeter-master-qqzxg
Name:         jmeter-master-qqzxg
Namespace:    default
Priority:     0
Node:         worker2/10.171.91.197
Start Time:   Mon, 13 Dec 2021 09:05:57 -0500
Labels:       controller-uid=6f314e1a-6836-445b-ba39-9681b391bad6
              jmeter_mode=master
              job-name=jmeter-master
Annotations:  cni.projectcalico.org/podIP: 10.42.9.117/32
              cni.projectcalico.org/podIPs: 10.42.9.117/32
              telegraf.influxdata.com/class: app
              telegraf.influxdata.com/inputs:
                [[inputs.jolokia2_agent]]
                  urls = ["http://localhost:8778/jolokia"]
                
                  [[inputs.jolokia2_agent.metric]]
                    name  = "java_runtime"
                    mbean = "java.lang:type=Runtime"
                    paths = ["Uptime"]
                
                  [[inputs.jolokia2_agent.metric]]
                    name  = "java_memory"
                    mbean = "java.lang:type=Memory"
                    paths = ["HeapMemoryUsage", "NonHeapMemoryUsage", "ObjectPendingFinalizationCount"]
                
                  [[inputs.jolokia2_agent.metric]]
                    name     = "java_garbage_collector"
                    mbean    = "java.lang:name=*,type=GarbageCollector"
                    paths    = ["CollectionTime", "CollectionCount"]
                    tag_keys = ["name"]
                
                  [[inputs.jolokia2_agent.metric]]
                    name  = "java_last_garbage_collection"
                    mbean = "java.lang:name=G1 Young Generation,type=GarbageCollector"
                    paths = ["LastGcInfo/duration", "LastGcInfo/GcThreadCount", "LastGcInfo/memoryUsageAfterGc"]
                
                  [[inputs.jolokia2_agent.metric]]
                    name  = "java_threading"
                    mbean = "java.lang:type=Threading"
                    paths = ["TotalStartedThreadCount", "ThreadCount", "DaemonThreadCount", "PeakThreadCount"]
                
                  [[inputs.jolokia2_agent.metric]]
                    name  = "java_class_loading"
                    mbean = "java.lang:type=ClassLoading"
                    paths = ["LoadedClassCount", "UnloadedClassCount", "TotalLoadedClassCount"]
                
                  [[inputs.jolokia2_agent.metric]]
                    name     = "java_memory_pool"
                    mbean    = "java.lang:name=*,type=MemoryPool"
                    paths    = ["Usage", "PeakUsage", "CollectionUsage"]
                    tag_keys = ["name"]
                
                [[inputs.jolokia]]
                  context = "/jolokia/"
                [[inputs.jolokia.servers]]
                  host = "127.0.0.1"
                  port = "8778"
                [[inputs.jolokia.metrics]]
                  name = "heap_memory_usage"
                  mbean  = "java.lang:type=Memory"
                  attribute = "HeapMemoryUsage"
                [[inputs.jolokia.metrics]]
                  name = "thread_count"
                  mbean  = "java.lang:type=Threading"
                  attribute = "TotalStartedThreadCount,ThreadCount,DaemonThreadCount,PeakThreadCount"
Status:       Running
IP:           10.42.9.117
IPs:
  IP:           10.42.9.117
Controlled By:  Job/jmeter-master
Containers:
  jmmaster:
    Container ID:  docker://5a31f5e92c03f6778493b37ba914a534f24e29ff1d0b5cf762127f7fc99051a6
    Image:         rbillon59/jmeter-k8s-base:5.4.1
    Image ID:      docker-pullable://rbillon59/jmeter-k8s-base@sha256:dd74e89bbc1f3ccdffb28b8c115fce73891a3ee365ce833f291b565a217f3503
    Port:          60000/TCP
    Host Port:     0/TCP
    Command:
      /bin/bash
    Args:
      -c
      trap 'exit 0' SIGUSR1 && while true; do sleep 30;done
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 13 Dec 2021 09:07:03 -0500
      Finished:     Mon, 13 Dec 2021 09:08:03 -0500
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1024m
      memory:  2Gi
    Requests:
      cpu:     1024m
      memory:  1Gi
    Liveness:  exec [cat /opt/jmeter/apache-jmeter/bin/jmeter] delay=5s timeout=1s period=5s #success=1 #failure=3
    Environment:
      MODE:       MASTER
      NODE_NAME:   (v1:spec.nodeName)
      POD_NAME:   jmeter-master-qqzxg (v1:metadata.name)
      NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /report from jmeter-data-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-l65cf (ro)
  telegraf:
    Container ID:   docker://57309edf15874f2ddd6f1f53f04c10ed428db3bc91bffee88e54743af964d308
    Image:          docker.io/library/telegraf:1.14
    Image ID:       docker-pullable://telegraf@sha256:32fd7cc8528ec27f94a83da19c2dba48fa01d7120a98845ecd28fd0313f2adf0
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Mon, 13 Dec 2021 09:07:03 -0500
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  200Mi
    Requests:
      cpu:     10m
      memory:  10Mi
    Environment:
      NODENAME:   (v1:spec.nodeName)
    Mounts:
      /etc/telegraf from telegraf-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-l65cf (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  jmeter-data-dir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  jmeter-data-dir-pvc
    ReadOnly:   false
  default-token-l65cf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-l65cf
    Optional:    false
  telegraf-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  telegraf-config-jmeter-master-qqzxg
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age    From                     Message
  ----     ------                  ----   ----                     -------
  Normal   Scheduled               8m25s  default-scheduler        Successfully assigned default/jmeter-master-qqzxg to worker2
  Warning  FailedAttachVolume      8m25s  attachdetach-controller  Multi-Attach error for volume "pvc-332a608c-25c4-4d50-8769-1d86d13ca658" Volume is already used by pod(s) jmeter-master-j2kkj
  Normal   SuccessfulAttachVolume  7m38s  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-332a608c-25c4-4d50-8769-1d86d13ca658"
  Normal   Pulling                 7m20s  kubelet                  Pulling image "rbillon59/jmeter-k8s-base:5.4.1"
  Normal   Pulled                  7m19s  kubelet                  Successfully pulled image "rbillon59/jmeter-k8s-base:5.4.1" in 291.832393ms
  Normal   Created                 7m19s  kubelet                  Created container jmmaster
  Normal   Started                 7m19s  kubelet                  Started container jmmaster
  Normal   Pulled                  7m19s  kubelet                  Container image "docker.io/library/telegraf:1.14" already present on machine
  Normal   Created                 7m19s  kubelet                  Created container telegraf
  Normal   Started                 7m19s  kubelet                  Started container telegraf
  Warning  Unhealthy               6m19s  kubelet                  Liveness probe failed: cannot exec in a stopped state: unknown
`

`09:14:22 airflow@paqctdm:[~]: kubectl describe pod jmeter-slaves-4ss74
Name:         jmeter-slaves-4ss74
Namespace:    default
Priority:     0
Node:         worker3/10.171.89.193
Start Time:   Mon, 13 Dec 2021 09:06:00 -0500
Labels:       controller-uid=3935be65-fa25-43b2-bdc7-ea2dc318d815
              jmeter_mode=slave
              job-name=jmeter-slaves
Annotations:  cni.projectcalico.org/podIP: 10.42.12.52/32
              cni.projectcalico.org/podIPs: 10.42.12.52/32
              telegraf.influxdata.com/class: app
              telegraf.influxdata.com/inputs:
                [[inputs.jolokia2_agent]]
                  urls = ["http://localhost:8778/jolokia"]
                
                  [[inputs.jolokia2_agent.metric]]
                    name  = "java_runtime"
                    mbean = "java.lang:type=Runtime"
                    paths = ["Uptime"]
                
                  [[inputs.jolokia2_agent.metric]]
                    name  = "java_memory"
                    mbean = "java.lang:type=Memory"
                    paths = ["HeapMemoryUsage", "NonHeapMemoryUsage", "ObjectPendingFinalizationCount"]
                
                  [[inputs.jolokia2_agent.metric]]
                    name     = "java_garbage_collector"
                    mbean    = "java.lang:name=*,type=GarbageCollector"
                    paths    = ["CollectionTime", "CollectionCount"]
                    tag_keys = ["name"]
                
                  [[inputs.jolokia2_agent.metric]]
                    name  = "java_last_garbage_collection"
                    mbean = "java.lang:name=G1 Young Generation,type=GarbageCollector"
                    paths = ["LastGcInfo/duration", "LastGcInfo/GcThreadCount", "LastGcInfo/memoryUsageAfterGc"]
                
                  [[inputs.jolokia2_agent.metric]]
                    name  = "java_threading"
                    mbean = "java.lang:type=Threading"
                    paths = ["TotalStartedThreadCount", "ThreadCount", "DaemonThreadCount", "PeakThreadCount"]
                
                  [[inputs.jolokia2_agent.metric]]
                    name  = "java_class_loading"
                    mbean = "java.lang:type=ClassLoading"
                    paths = ["LoadedClassCount", "UnloadedClassCount", "TotalLoadedClassCount"]
                
                  [[inputs.jolokia2_agent.metric]]
                    name     = "java_memory_pool"
                    mbean    = "java.lang:name=*,type=MemoryPool"
                    paths    = ["Usage", "PeakUsage", "CollectionUsage"]
                    tag_keys = ["name"]
                
                [[inputs.jolokia]]
                  context = "/jolokia/"
                [[inputs.jolokia.servers]]
                  host = "127.0.0.1"
                  port = "8778"
                [[inputs.jolokia.metrics]]
                  name = "heap_memory_usage"
                  mbean  = "java.lang:type=Memory"
                  attribute = "HeapMemoryUsage"
                [[inputs.jolokia.metrics]]
                  name = "thread_count"
                  mbean  = "java.lang:type=Threading"
                  attribute = "TotalStartedThreadCount,ThreadCount,DaemonThreadCount,PeakThreadCount"
Status:       Running
IP:           10.42.12.52
IPs:
  IP:           10.42.12.52
Controlled By:  Job/jmeter-slaves
Containers:
  jmslave:
    Container ID:  docker://f4f848d90c1c00fd307147b64e13b233e4064f2296ab22721113b0e0e9622dbd
    Image:         rbillon59/jmeter-k8s-base:5.4.1
    Image ID:      docker-pullable://rbillon59/jmeter-k8s-base@sha256:dd74e89bbc1f3ccdffb28b8c115fce73891a3ee365ce833f291b565a217f3503
    Ports:         1099/TCP, 50000/TCP, 4445/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/bash
    Args:
      -c
      trap 'exit 0' SIGUSR1 && while true; do sleep 30;done
    State:          Running
      Started:      Mon, 13 Dec 2021 09:06:01 -0500
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1024m
      memory:  1Gi
    Requests:
      cpu:     1024m
      memory:  1Gi
    Liveness:  exec [cat /opt/jmeter/apache-jmeter/bin/jmeter] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      MODE:  SLAVE
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-l65cf (ro)
  telegraf:
    Container ID:   docker://e86f5bfc827f5f3d91ce2bb8348a9090378cbaac091c72a6c35ec107a417bb0c
    Image:          docker.io/library/telegraf:1.14
    Image ID:       docker-pullable://telegraf@sha256:32fd7cc8528ec27f94a83da19c2dba48fa01d7120a98845ecd28fd0313f2adf0
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Mon, 13 Dec 2021 09:06:01 -0500
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  200Mi
    Requests:
      cpu:     10m
      memory:  10Mi
    Environment:
      NODENAME:   (v1:spec.nodeName)
    Mounts:
      /etc/telegraf from telegraf-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-l65cf (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-l65cf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-l65cf
    Optional:    false
  telegraf-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  telegraf-config-jmeter-slaves-4ss74
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  9m12s  default-scheduler  Successfully assigned default/jmeter-slaves-4ss74 to worker3
  Normal  Pulling    9m12s  kubelet            Pulling image "rbillon59/jmeter-k8s-base:5.4.1"
  Normal  Pulled     9m12s  kubelet            Successfully pulled image "rbillon59/jmeter-k8s-base:5.4.1" in 259.707985ms
  Normal  Created    9m12s  kubelet            Created container jmslave
  Normal  Started    9m12s  kubelet            Started container jmslave
  Normal  Pulled     9m12s  kubelet            Container image "docker.io/library/telegraf:1.14" already present on machine
  Normal  Created    9m12s  kubelet            Created container telegraf
  Normal  Started    9m12s  kubelet            Started container telegraf`

I have retry tests this morning and I have the same behaviour.
Thank you for your time. As you might have understood I am not a kubernetes expert yet.

**Comment by Davmira** [comment]
I have tested with minikube and it's working well :
![working minikube jemter](https://user-images.githubusercontent.com/6617187/145882836-7a09fd56-2422-4ca9-843f-116229f10d9d.png)

I still have the warning but the start command don't stop after the warning, I just have to, like you said before, to cancel the command using CTRL + C and I am able to get the result.
But, when I am doing this using my cluster the start command stopped and the master pod crash ...

**Comment by Rbillon59** [comment]
Ok, I'm not totally crazy.

Yeah, the warning is really not something to care about. It is only linked to plugin install and not test start.

I will try to reproduce that on a rancher 2 farm locally

**Comment by Rbillon59** [comment]
I tried locally deploying rancher. And I needed to manually create persistantVolumes because there was no default storage class. But apart from this, I was able to run the demo project witnout any problem :


As the master pod is deploying without any problem I support you haven't problems with your storage configuration ? I saw in the describe of the master pod that you the scheduler had problem with the volume claim for a minute : 

  Warning  FailedAttachVolume      8m25s  attachdetach-controller  Multi-Attach error for volume "pvc-332a608c-25c4-4d50-8769-1d86d13ca658" Volume is already used by pod(s) jmeter-master-j2kkj

**Comment by Davmira** [comment]
Hi again,

You are right about the warning. But I have tested without the job which recreate the master pod (kubectl delete job jmeter-master) and without a master pod at start. I get the same result, tests are stopped for some reason : 
![delete master pod before](https://user-images.githubusercontent.com/6617187/146087730-7782336d-040e-456b-a484-e83fc98ab0f2.png)

I have retested on minikube it still woking well. The only difference I can see between rancher and minikube is that I have a telegraf container inside the master pod which I don't have inside the master pod for minikube : 
![rancher vs minikube telegraf thing](https://user-images.githubusercontent.com/6617187/146087899-3056be31-2b92-4ed5-9c17-dd7370d46311.png)

It getting me crazy even if I learn lot's of stuffs. The project is running on minikube and it fit perfectly with what I need. I have also checked, everything seems right on openstack for the volumes.
On rancher I can get more details when the master pod has finished : 

![rancher_master_pod_finishing_without_contaxt](https://user-images.githubusercontent.com/6617187/146088192-2789344b-8b4f-47d5-9141-40725fa4ab7c.png)

Since I don't have any errors inside my pods stdout it is possible to have some logs about the jmeter execution ?
Thanks

**Comment by Rbillon59** [comment]
For the telegraf stuff, it's maybe because I pushed a fix this noon about the telegraf operator that did not deployed sidecar correctly. Would you retry ?

I continue to dig on my side to understand what could go wrong on your setup. But in the dedicaced JMeter image I made, every jmeter logs are redirected to stdout.

![image](https://user-images.githubusercontent.com/17565349/146091686-6bd6682c-7627-4dcf-90a3-cb9976a055d6.png)

Does the container finish in completed state ? Because in your first screenshot, it appears to be in "Running" state. 

Openstack is a bit tricky to deploy locally to test with Rancher so it's pretty hard to reproduce on my side.

Maybe, you could try to play with the liveness timeout or something related ?

Also, maybe you could try to find some logs related to the Kubernetes scheduler. I work a lot with Lens which is an IDE for the Kubernetes cluster and helped me a lot debugging my resources.

Thanks you

**Comment by Davmira** [comment]
Hi @Rbillon59 

I am working in Montreal and I have pulled each day your last commit from master so I was up to date.
I still have the same issue today.
I have tried to lower the number of worker from 6 to 2.
I have changed the image from the workers from centos7 to ubuntu.

At the end of the performance test, the master pod has the status 'Running' for like 10 secondes. After those 10 secondes it changes to 'NotReady' :
![start bug no end execution](https://user-images.githubusercontent.com/6617187/146231296-5a8eb55a-4231-4452-9b47-7f03f71e7613.png)

I have checked the yml of the pod at the end of the execution, if it can help :
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-12-15T15:54:11Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-12-15T15:55:44Z"
    message: 'containers with unready status: [jmmaster]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-12-15T15:55:44Z"
    message: 'containers with unready status: [jmmaster]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-12-15T15:54:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://a889cf5e7554f02d06fecf2413a0639ea9939a002aeb75f21ca159f36ebbd125
    image: rbillon59/jmeter-k8s-base:5.4.1
    imageID: docker-pullable://rbillon59/jmeter-k8s-base@sha256:d405117e1ec055a9d3a22e648b4b1770956f983fb546200f6f220a3feada9602
    lastState: {}
    name: jmmaster
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://a889cf5e7554f02d06fecf2413a0639ea9939a002aeb75f21ca159f36ebbd125
        exitCode: 0
        finishedAt: "2021-12-15T15:55:44Z"
        reason: Completed
        startedAt: "2021-12-15T15:54:14Z"
  - containerID: docker://dec311e39113669347d6093c7757d13ce886e1c1f87782df019c02101a001e6d
    image: telegraf:1.14
    imageID: docker-pullable://telegraf@sha256:32fd7cc8528ec27f94a83da19c2dba48fa01d7120a98845ecd28fd0313f2adf0
    lastState: {}
    name: telegraf
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-12-15T15:54:19Z"
  hostIP: 10.171.92.237
  phase: Running
  podIP: 10.42.21.11
  podIPs:
  - ip: 10.42.21.11
  qosClass: Burstable
  startTime: "2021-12-15T15:54:11Z"
```
In fact, the master pod has the status 'NotReady', inside the telegraf container is working well with a 'Ready' status but the container jmmaster has the status 'NotReady' : 
![master pod with container not ready and ready](https://user-images.githubusercontent.com/6617187/146231826-62290603-7e27-468c-82e3-b6a4f5c5c129.png)

When I go inside the conditions status I don't get usefull informations : 
![rancher master pod condition not usefull](https://user-images.githubusercontent.com/6617187/146231970-fe48c05b-7d2d-4aa3-b714-81460e35bca5.png)


But I think I made good progress this morning. I might have found my issue which is link to the volume. I think jmmeter container can't write the report output file which made the performance test crashed : 
![usefull logs from jmmeter container inside master pod](https://user-images.githubusercontent.com/6617187/146232205-381e0f8f-bd21-4d1e-a44f-9c0bc5381fe6.png)

In case it can helps, I get this result running this command : kubectl logs jmeter-master-rlxg8 jmmaster (kubectl logs <master pod id> <container>

Can you confirm my problem is linked to this error message : 
**java.lang.IllegalArgumentException: Cannot write to '/report/report-my-scenario.jmx-2021-12-15_105501' as folder does not exist and parent folder is not writable**

**Comment by Rbillon59** [comment]
Hi thanks for the details !

I'll try tomorrow to run a test asking the master to write the report to a folder where it has no permissions and see if the test continue to be executed or it crash immediately.

But obviously, you need to fix this, even to recover your jtl.

I'm curious about what could cause this permissions problem or mounting errors.

**Comment by Davmira** [comment]
Ok so I have checked the difference between minikube and rancher for the permission at the root of the master pod. In minikube the report folder has full rights for each user when in rancher only the root user has full right, otherwise all others user only have execution permission : 
Minikube : 
![permission at the root of the master pod minikube](https://user-images.githubusercontent.com/6617187/146252826-7684966b-96f2-4744-bb40-4ab69a99997a.png)

Rancher : 
![permission at the root of the master pod](https://user-images.githubusercontent.com/6617187/146252834-5c7e1472-64f6-46f3-8606-a8c3f4f07367.png)

Now I need to learn how to fix this 😄

**Comment by Rbillon59** [comment]
Well done !

I think it's because Rancher as a safer default approach in terms of security. 

In the pod specifications, you can force the mount path to be writable for a specific Gid by setting a security context. I did not remember the jmeter group gid. I'll check it tomorrow. But if you can before, you just have to run the Id command in a slave pod to get it.

Adding the below lines with the right gid in the master pod specification would do the trick.

```yml
spec:
      securityContext:
        fsGroup: 1000
```

**Comment by Davmira** [comment]
Thanks you for the quick reply.
I am so glad it's working now !
If I am not wrong the jmeter group gid is like in your example, 1000 : 

![groupd id jmeter id commadn](https://user-images.githubusercontent.com/6617187/146272043-b686d2e9-6ab0-49bf-87d5-21b74e72300b.png)

I have added the code inside the master pod yml and it's working. It's not perfect because I have to cancel the test when I have the 'WARN Unable to register Log4j shutdown '. And now my master and slave pods change to 'NotReady' after 10 secondes : 
![jmslave not ready](https://user-images.githubusercontent.com/6617187/146272449-c7aa752f-e345-4758-8db3-af723ed60589.png)

But I am able to get the results !

**Comment by Rbillon59** [comment]
It's seems to be the "normal" behaviour in some way, because the master and the slaves are working as Kubernetes jobs. So when completed, the JMeter container shutdown. 

Also there is a cleaner running every minutes as cronjob that should delete the JMeter jobs to free the resources. But because the telegraf operator put a sidecar container, when the JMeter job is completed and the jmeter container  deleted, it remains only the telegraf container inside the pod.

As far I've tested, the complete pod should be destroyed when the job is completed. But maybe there was a change in the telegraf operator. I'll dig that tomorrow.

Don't worry pressing ctrl+c while launching the test, it's really linked to the plugin management.

Anyway, the weirdest thing is you haven't any data back in Grafana. But hey, you struggled to write in /report with the JMeter master. As I provisioned a persistent volume to mount for the influxdb data. I bet you've the very same problem for Influxdb to write on the mounted volume. Could you try to find the Influx logs please ?

Thanks you

**Comment by Davmira** [comment]
Ok I get it for the cleaner not doing its job because of one of the container still running healthy.

Because 24h later, my pods are still there with 'NotReady' and 'CrashLoopBackOff' status for influxdb : 
 
![Screenshot from 2021-12-16 15-50-09](https://user-images.githubusercontent.com/6617187/146447312-fa801698-c5bd-43a9-8a0a-76a8b4f0db38.png)

Here the logs of influx container running : kubectl logs influxdb-d6f8b6c89-rvc8t influxdb : 
```
ts=2021-12-16T20:36:04.560514Z lvl=info msg="InfluxDB starting" log_id=0YTFBeK0000 version=1.8.10 branch=1.8 commit=688e697c51fd
ts=2021-12-16T20:36:04.560537Z lvl=info msg="Go runtime" log_id=0YTFBeK0000 version=go1.13.8 maxprocs=4
ts=2021-12-16T20:36:04.662368Z lvl=info msg="Using data dir" log_id=0YTFBeK0000 service=store path=/var/lib/influxdb/data
ts=2021-12-16T20:36:04.662403Z lvl=info msg="Compaction settings" log_id=0YTFBeK0000 service=store max_concurrent_compactions=2 throughput_bytes_per_second=50331648 throughput_bytes_per_second_burst=50331648
ts=2021-12-16T20:36:04.662413Z lvl=info msg="Open store (start)" log_id=0YTFBeK0000 service=store trace_id=0YTFBeiW000 op_name=tsdb_open op_event=start
ts=2021-12-16T20:36:04.675704Z lvl=info msg="Reading file" log_id=0YTFBeK0000 engine=tsm1 service=cacheloader path=/var/lib/influxdb/wal/_internal/monitor/3/_00001.wal size=10489156
ts=2021-12-16T20:36:04.685486Z lvl=info msg="Opened file" log_id=0YTFBeK0000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/_internal/monitor/2/000000001-000000001.tsm id=0 duration=9.314ms
ts=2021-12-16T20:36:04.769633Z lvl=info msg="Opened shard" log_id=0YTFBeK0000 service=store trace_id=0YTFBeiW000 op_name=tsdb_open index_version=inmem path=/var/lib/influxdb/data/_internal/monitor/2 duration=96.091ms
ts=2021-12-16T20:36:04.887026Z lvl=info msg="Opened file" log_id=0YTFBeK0000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/telegraf/autogen/1/000000052-000000001.tsm id=2 duration=105.827ms
ts=2021-12-16T20:36:04.887512Z lvl=info msg="Opened file" log_id=0YTFBeK0000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/telegraf/autogen/1/000000051-000000002.tsm id=1 duration=111.819ms
ts=2021-12-16T20:36:04.969395Z lvl=info msg="Opened file" log_id=0YTFBeK0000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/telegraf/autogen/1/000000037-000000003.tsm id=0 duration=193.752ms
ts=2021-12-16T20:36:04.973061Z lvl=info msg="Opened file" log_id=0YTFBeK0000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/telegraf/autogen/1/000000056-000000001.tsm id=4 duration=85.468ms
ts=2021-12-16T20:36:04.983021Z lvl=info msg="Opened file" log_id=0YTFBeK0000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/telegraf/autogen/1/000000054-000000001.tsm id=3 duration=94.738ms
ts=2021-12-16T20:36:04.999058Z lvl=info msg="Opened file" log_id=0YTFBeK0000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/telegraf/autogen/1/000000064-000000001.tsm id=8 duration=223.368ms
ts=2021-12-16T20:36:05.003621Z lvl=info msg="Opened file" log_id=0YTFBeK0000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/telegraf/autogen/1/000000058-000000001.tsm id=5 duration=34.148ms
ts=2021-12-16T20:36:05.070370Z lvl=info msg="Opened file" log_id=0YTFBeK0000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/telegraf/autogen/1/000000062-000000001.tsm id=7 duration=87.298ms
ts=2021-12-16T20:36:05.076085Z lvl=info msg="Opened file" log_id=0YTFBeK0000 engine=tsm1 service=filestore path=/var/lib/influxdb/data/telegraf/autogen/1/000000060-000000001.tsm id=6 duration=102.969ms
ts=2021-12-16T20:36:05.076250Z lvl=info msg="Reading file" log_id=0YTFBeK0000 engine=tsm1 service=cacheloader path=/var/lib/influxdb/wal/telegraf/autogen/1/_00494.wal size=10556965
ts=2021-12-16T20:36:07.372134Z lvl=info msg="Reading file" log_id=0YTFBeK0000 engine=tsm1 service=cacheloader path=/var/lib/influxdb/wal/telegraf/autogen/1/_00495.wal size=4623757
ts=2021-12-16T20:36:08.176478Z lvl=info msg="Reading file" log_id=0YTFBeK0000 engine=tsm1 service=cacheloader path=/var/lib/influxdb/wal/_internal/monitor/3/_00002.wal size=10489288
ts=2021-12-16T20:36:09.265196Z lvl=info msg="Opened shard" log_id=0YTFBeK0000 service=store trace_id=0YTFBeiW000 op_name=tsdb_open index_version=inmem path=/var/lib/influxdb/data/telegraf/autogen/1 duration=4495.509ms
ts=2021-12-16T20:36:10.466474Z lvl=info msg="Reading file" log_id=0YTFBeK0000 engine=tsm1 service=cacheloader path=/var/lib/influxdb/wal/_internal/monitor/3/_00003.wal size=2858560
ts=2021-12-16T20:36:10.903401Z lvl=info msg="Opened shard" log_id=0YTFBeK0000 service=store trace_id=0YTFBeiW000 op_name=tsdb_open index_version=inmem path=/var/lib/influxdb/data/_internal/monitor/3 duration=6229.830ms
ts=2021-12-16T20:36:10.903537Z lvl=info msg="Open store (end)" log_id=0YTFBeK0000 service=store trace_id=0YTFBeiW000 op_name=tsdb_open op_event=end op_elapsed=6241.124ms
ts=2021-12-16T20:36:10.903584Z lvl=info msg="Opened service" log_id=0YTFBeK0000 service=subscriber
ts=2021-12-16T20:36:10.903603Z lvl=info msg="Starting monitor service" log_id=0YTFBeK0000 service=monitor
ts=2021-12-16T20:36:10.903612Z lvl=info msg="Registered diagnostics client" log_id=0YTFBeK0000 service=monitor name=build
ts=2021-12-16T20:36:10.903623Z lvl=info msg="Registered diagnostics client" log_id=0YTFBeK0000 service=monitor name=runtime
ts=2021-12-16T20:36:10.903628Z lvl=info msg="Registered diagnostics client" log_id=0YTFBeK0000 service=monitor name=network
ts=2021-12-16T20:36:10.903681Z lvl=info msg="Registered diagnostics client" log_id=0YTFBeK0000 service=monitor name=system
ts=2021-12-16T20:36:10.903708Z lvl=info msg="Starting precreation service" log_id=0YTFBeK0000 service=shard-precreation check_interval=10m advance_period=30m
ts=2021-12-16T20:36:10.903719Z lvl=info msg="Starting snapshot service" log_id=0YTFBeK0000 service=snapshot
ts=2021-12-16T20:36:10.903728Z lvl=info msg="Starting continuous query service" log_id=0YTFBeK0000 service=continuous_querier
ts=2021-12-16T20:36:10.903745Z lvl=info msg="Starting HTTP service" log_id=0YTFBeK0000 service=httpd authentication=false
ts=2021-12-16T20:36:10.903750Z lvl=info msg="opened HTTP access log" log_id=0YTFBeK0000 service=httpd path=stderr
ts=2021-12-16T20:36:10.903791Z lvl=info msg="Storing statistics" log_id=0YTFBeK0000 service=monitor db_instance=_internal db_rp=monitor interval=10s
ts=2021-12-16T20:36:10.904029Z lvl=info msg="Listening on HTTP" log_id=0YTFBeK0000 service=httpd addr=[::]:8086 https=false
ts=2021-12-16T20:36:10.904054Z lvl=info msg="Starting retention policy enforcement service" log_id=0YTFBeK0000 service=retention check_interval=30m
ts=2021-12-16T20:36:10.904185Z lvl=info msg="Listening for signals" log_id=0YTFBeK0000
ts=2021-12-16T20:36:10.904637Z lvl=info msg="Sending usage statistics to usage.influxdata.com" log_id=0YTFBeK0000
[httpd] 10.42.26.6 - user [16/Dec/2021:20:36:20 +0000] "POST /write?db=telegraf HTTP/1.1 " 204 0 "-" "-" d38ae914-5eaf-11ec-8001-26b188b37fee 667852
[httpd] 10.42.27.4 - user [16/Dec/2021:20:36:20 +0000] "POST /write?db=telegraf HTTP/1.1 " 400 190902 "-" "-" d38afa02-5eaf-11ec-8003-26b188b37fee 671709
[httpd] 10.42.25.4 - user [16/Dec/2021:20:36:20 +0000] "POST /write?db=telegraf HTTP/1.1 " 400 382482 "-" "-" d38b42dd-5eaf-11ec-8005-26b188b37fee 761836
[httpd] 10.42.23.18 - user [16/Dec/2021:20:36:20 +0000] "POST /write?db=telegraf HTTP/1.1 " 400 164819 "-" "-" d38af892-5eaf-11ec-8002-26b188b37fee 772765
[httpd] 10.42.24.5 - user [16/Dec/2021:20:36:20 +0000] "POST /write?db=telegraf HTTP/1.1 " 400 190932 "-" "-" d38d6412-5eaf-11ec-8006-26b188b37fee 849683
[httpd] 10.42.21.14 - user [16/Dec/2021:20:36:20 +0000] "POST /write?db=telegraf HTTP/1.1 " 400 380244 "-" "-" d38afbc0-5eaf-11ec-8004-26b188b37fee 1075949
[httpd] 10.42.26.6 - user [16/Dec/2021:20:36:21 +0000] "POST /write?db=telegraf HTTP/1.1 " 204 0 "-" "-" d3fe8df7-5eaf-11ec-8007-26b188b37fee 518142
[httpd] 10.42.27.4 - user [16/Dec/2021:20:36:21 +0000] "POST /write?db=telegraf HTTP/1.1 " 400 222713 "-" "-" d3fe8df7-5eaf-11ec-8008-26b188b37fee 929475
[httpd] 10.42.23.18 - user [16/Dec/2021:20:36:21 +0000] "POST /write?db=telegraf HTTP/1.1 " 400 185163 "-" "-" d40dd1a3-5eaf-11ec-800a-26b188b37fee 900042
[httpd] 10.42.25.4 - user [16/Dec/2021:20:36:21 +0000] "POST /write?db=telegraf HTTP/1.1 " 400 414406 "-" "-" d400fb46-5eaf-11ec-8009-26b188b37fee 1086628
[httpd] 10.42.21.14 - user [16/Dec/2021:20:36:21 +0000] "POST /write?db=telegraf HTTP/1.1 " 400 348686 "-" "-" d43b9d8b-5eaf-11ec-800c-26b188b37fee 703394
[httpd] 10.42.24.5 - user [16/Dec/2021:20:36:21 +0000] "POST /write?db=telegraf HTTP/1.1 " 400 222748 "-" "-" d41d14f6-5eaf-11ec-800b-26b188b37fee 909378
[httpd] 10.42.26.6 - user [16/Dec/2021:20:36:21 +0000] "POST /write?db=telegraf HTTP/1.1 " 204 0 "-" "-" d45ba049-5eaf-11ec-800d-26b188b37fee 499996
[httpd] 10.42.27.4 - user [16/Dec/2021:20:36:22 +0000] "POST /write?db=telegraf HTTP/1.1 " 400 222713 "-" "-" d49727bb-5eaf-11ec-800e-26b188b37fee 405440
[httpd] 10.42.23.18 - user [16/Dec/2021:20:36:22 +0000] "POST /write?db=telegraf HTTP/1.1 " 400 159086 "-" "-" d4a6d1f2-5eaf-11ec-800f-26b188b37fee 312104
```

Like you are saying, I am not sure if everything is working well for grafana here some screenshots : 
![Screenshot from 2021-12-16 16-21-30](https://user-images.githubusercontent.com/6617187/146450761-c455c747-6c89-4f59-8907-83b1b9adaa5f.png)
![Screenshot from 2021-12-16 16-21-09](https://user-images.githubusercontent.com/6617187/146450762-af7915f5-1510-44cd-a9ce-709397e14e33.png)

**Comment by Rbillon59** [comment]
Hi !

As far I can say, data are written to influxdb because you was able to graph it. 
By default, the demo is reaching google.com. Is there anything that would block the traffic from your rancher farm to the external network ?

Because here I'm just seeing that things works.

In fact, the master and slaves being in not ready stats is obviously because they have completed their jobs. If you want to test something else, you can just update the variables in the .env file in the scenario/my-scenario folder with a longer duration.

Just, you should take a look at the cleaner cronjob. I suspect it do not work well in your configuration and I don't really understand why. Because, every minutes, it should clean master and slaves jobs completely if they are done.

Could you provide me some logs about the cleaner cronjob please ?

I'm happy things are getting closer to work for you !

**Comment by Davmira** [comment]
Hey,

I think that data are written too to influxdb because I am able to see some graphs.

I don't have any cronjobs :

![Screenshot from 2021-12-17 15-51-44](https://user-images.githubusercontent.com/6617187/146607412-8d7c0f40-7f87-468e-ba9f-c497770294af.png)

I have pull the code to be sure before ...

**Comment by Rbillon59** [comment]
If you've created the resources with kubectl create -R -f k8s/ the cleaner job should have been created. 

But anyway, it's not a problem because every time you start a test, JMeter job are deleted and created again. You just waste few resources with the sidecar containers that are still up and running.

I'll push the permission fix for the master soon. Thanks you for helping me to improve this project.

**Comment by Davmira** [comment]
Thank you for your time helping me :+1:
